from fastapi import APIRouter, status

from app.schemas.planning import GoalRequest, PlanResponse, Milestone, Task

router = APIRouter(prefix="/goals", tags=["Goals"])


@router.post("/plan", response_model=PlanResponse, status_code=status.HTTP_201_CREATED)
async def create_plan(payload: GoalRequest) -> PlanResponse:
    """
    Receive a user goal and return a structured plan.

    For now, this returns dummy data so that the frontend
    and overall architecture can be wired up.
    Later, this will call Kestra + Oumi.
    """

    # TODO: Replace this with a call to Kestra workflow + Oumi agent.
    dummy_milestones = [
    Milestone(
        title="Understand the basics",
        description="Learn the fundamental concepts",
    ),
    Milestone(
        title="Practice with small tasks",
        description="Apply knowledge with practical exercises",
    ),
]

    dummy_tasks = [
        Task(
            id="1",
            task="Read introduction materials for 30 minutes",
            milestone=dummy_milestones[0].title,
            duration_minutes=30,
        ),
        Task(
            id="2",
            task="Do one small practice exercise",
            milestone=dummy_milestones[1].title,
            duration_minutes=45,
        ),
    ]

    return PlanResponse(
        goal=payload.goal,
        milestones=dummy_milestones,
        tasks=dummy_tasks,
        schedule_summary=(
            f"Placeholder plan for goal: {payload.goal}. "
            "In the full version, this will be generated by the TaskPilot planning agent."
        ),
    )
